--- #YAML:1.0
name:                Archive-Extract
version:             0.34
abstract:            Generic archive extracting mechanism
license:             ~
author:              
    - Jos Boumans <kane[at]cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Basename:                0
    File::Path:                    0
    File::Spec:                    0.82
    IPC::Cmd:                      0.42
    Locale::Maketext::Simple:      0
    Module::Load::Conditional:     0.04
    Params::Check:                 0.07
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
